# Generated by Django 5.0 on 2024-01-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0001_initial'),
    ]
    

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='hosteler',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
