# Generated by Django 5.0 on 2024-01-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0002_transaction_alter_hosteler_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hosteler',
            new_name='Student',
        ),
    ]
