# Generated by Django 5.0 on 2024-01-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0003_rename_hosteler_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1),
        ),
    ]
