# Generated by Django 5.0 on 2024-01-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0004_student_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
