# Generated by Django 5.0 on 2024-01-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Has', '0005_delete_student_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('Gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1)),
                ('Feedues', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.CharField(max_length=10)),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField()),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
