# Generated by Django 5.0 on 2024-01-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
