# Generated by Django 5.0 on 2024-01-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0007_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.CharField(max_length=10)),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField()),
                ('Transaction_Type', models.CharField(choices=[('C', 'CASH'), ('O', 'ONLINE PAYMENT')], default='C', max_length=1)),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
