# Generated by Django 5.0 on 2024-01-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0008_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Feedues',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Status',
        ),
    ]
