# Generated by Django 5.0 on 2024-01-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0009_remove_student_feedues_remove_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.CharField(default='B. Tech (CSE)', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Room',
            field=models.CharField(default='**', max_length=10),
        ),
    ]
