# Generated by Django 5.0 on 2024-01-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Has', '0012_room_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
